// Copyright (c) 2026, WH, All rights reserved.
// vector forward defs
#ifndef UTIL_VECTORS_FWD_H
#define UTIL_VECTORS_FWD_H

#include "types.h"
#include "glm/fwd.hpp"

using bvec1 = glm::bvec1;
using bvec2 = glm::bvec2;
using bvec3 = glm::bvec3;
using bvec4 = glm::bvec4;
using dvec2 = glm::dvec2;
using dvec3 = glm::dvec3;
using dvec4 = glm::dvec4;
using vec2 = glm::vec2;
using vec3 = glm::vec3;
using vec4 = glm::vec4;
using ivec2 = glm::i32vec2;
using ivec3 = glm::i32vec3;
using ivec4 = glm::i32vec4;
using lvec2 = glm::i64vec2;
using lvec3 = glm::i64vec3;
using lvec4 = glm::i64vec4;
using u8vec4 = glm::u8vec4;
using uvec2 = glm::u32vec2;
using uvec3 = glm::u32vec3;
using uvec4 = glm::u32vec4;
using ulvec2 = glm::u64vec2;
using ulvec3 = glm::u64vec3;
using ulvec4 = glm::u64vec4;

namespace vec {

extern f64 radians(f64);
extern f32 radians(f32);
extern f64 degrees(f64);
extern f32 degrees(f32);
extern dvec2 clamp(dvec2 const&, double, double);
extern dvec2 clamp(dvec2 const&, dvec2 const&, dvec2 const&);
extern dvec2 max(dvec2 const&, double);
extern dvec2 max(dvec2 const&, dvec2 const&);
extern dvec2 min(dvec2 const&, double);
extern dvec2 min(dvec2 const&, dvec2 const&);
extern dvec2 abs(dvec2 const&);
extern dvec2 ceil(dvec2 const&);
extern double length(dvec2 const&);
extern double distance(dvec2 const&, dvec2 const&);
extern double dot(dvec2 const&, dvec2 const&);
extern dvec2 floor(dvec2 const&);
extern dvec2 round(dvec2 const&);
extern dvec2 normalize(dvec2 const&);
extern dvec3 clamp(dvec3 const&, double, double);
extern dvec3 clamp(dvec3 const&, dvec3 const&, dvec3 const&);
extern dvec3 max(dvec3 const&, double);
extern dvec3 max(dvec3 const&, dvec3 const&);
extern dvec3 min(dvec3 const&, double);
extern dvec3 min(dvec3 const&, dvec3 const&);
extern dvec3 cross(dvec3 const&, dvec3 const&);
extern dvec3 abs(dvec3 const&);
extern dvec3 ceil(dvec3 const&);
extern double length(dvec3 const&);
extern double distance(dvec3 const&, dvec3 const&);
extern double dot(dvec3 const&, dvec3 const&);
extern dvec3 floor(dvec3 const&);
extern dvec3 round(dvec3 const&);
extern dvec3 normalize(dvec3 const&);
extern dvec4 clamp(dvec4 const&, double, double);
extern dvec4 clamp(dvec4 const&, dvec4 const&, dvec4 const&);
extern dvec4 max(dvec4 const&, double);
extern dvec4 max(dvec4 const&, dvec4 const&);
extern dvec4 min(dvec4 const&, double);
extern dvec4 min(dvec4 const&, dvec4 const&);
extern dvec4 abs(dvec4 const&);
extern dvec4 ceil(dvec4 const&);
extern double length(dvec4 const&);
extern double distance(dvec4 const&, dvec4 const&);
extern double dot(dvec4 const&, dvec4 const&);
extern dvec4 floor(dvec4 const&);
extern dvec4 round(dvec4 const&);
extern dvec4 normalize(dvec4 const&);
extern vec2 clamp(vec2 const&, float, float);
extern vec2 clamp(vec2 const&, vec2 const&, vec2 const&);
extern vec2 max(vec2 const&, float);
extern vec2 max(vec2 const&, vec2 const&);
extern vec2 min(vec2 const&, float);
extern vec2 min(vec2 const&, vec2 const&);
extern vec2 abs(vec2 const&);
extern vec2 ceil(vec2 const&);
extern float length(vec2 const&);
extern float distance(vec2 const&, vec2 const&);
extern float dot(vec2 const&, vec2 const&);
extern vec2 floor(vec2 const&);
extern vec2 round(vec2 const&);
extern vec2 normalize(vec2 const&);
extern vec3 clamp(vec3 const&, float, float);
extern vec3 clamp(vec3 const&, vec3 const&, vec3 const&);
extern vec3 max(vec3 const&, float);
extern vec3 max(vec3 const&, vec3 const&);
extern vec3 min(vec3 const&, float);
extern vec3 min(vec3 const&, vec3 const&);
extern vec3 cross(vec3 const&, vec3 const&);
extern vec3 abs(vec3 const&);
extern vec3 ceil(vec3 const&);
extern float length(vec3 const&);
extern float distance(vec3 const&, vec3 const&);
extern float dot(vec3 const&, vec3 const&);
extern vec3 floor(vec3 const&);
extern vec3 round(vec3 const&);
extern vec3 normalize(vec3 const&);
extern vec4 clamp(vec4 const&, float, float);
extern vec4 clamp(vec4 const&, vec4 const&, vec4 const&);
extern vec4 max(vec4 const&, float);
extern vec4 max(vec4 const&, vec4 const&);
extern vec4 min(vec4 const&, float);
extern vec4 min(vec4 const&, vec4 const&);
extern vec4 abs(vec4 const&);
extern vec4 ceil(vec4 const&);
extern float length(vec4 const&);
extern float distance(vec4 const&, vec4 const&);
extern float dot(vec4 const&, vec4 const&);
extern vec4 floor(vec4 const&);
extern vec4 round(vec4 const&);
extern vec4 normalize(vec4 const&);
extern ivec2 clamp(ivec2 const&, i32, i32);
extern ivec2 clamp(ivec2 const&, ivec2 const&, ivec2 const&);
extern ivec2 max(ivec2 const&, i32);
extern ivec2 max(ivec2 const&, ivec2 const&);
extern ivec2 min(ivec2 const&, i32);
extern ivec2 min(ivec2 const&, ivec2 const&);
extern ivec2 abs(ivec2 const&);
extern ivec3 clamp(ivec3 const&, i32, i32);
extern ivec3 clamp(ivec3 const&, ivec3 const&, ivec3 const&);
extern ivec3 max(ivec3 const&, i32);
extern ivec3 max(ivec3 const&, ivec3 const&);
extern ivec3 min(ivec3 const&, i32);
extern ivec3 min(ivec3 const&, ivec3 const&);
extern ivec3 abs(ivec3 const&);
extern ivec4 clamp(ivec4 const&, i32, i32);
extern ivec4 clamp(ivec4 const&, ivec4 const&, ivec4 const&);
extern ivec4 max(ivec4 const&, i32);
extern ivec4 max(ivec4 const&, ivec4 const&);
extern ivec4 min(ivec4 const&, i32);
extern ivec4 min(ivec4 const&, ivec4 const&);
extern ivec4 abs(ivec4 const&);
extern lvec2 clamp(lvec2 const&, i64, i64);
extern lvec2 clamp(lvec2 const&, lvec2 const&, lvec2 const&);
extern lvec2 max(lvec2 const&, i64);
extern lvec2 max(lvec2 const&, lvec2 const&);
extern lvec2 min(lvec2 const&, i64);
extern lvec2 min(lvec2 const&, lvec2 const&);
extern lvec2 abs(lvec2 const&);
extern lvec3 clamp(lvec3 const&, i64, i64);
extern lvec3 clamp(lvec3 const&, lvec3 const&, lvec3 const&);
extern lvec3 max(lvec3 const&, i64);
extern lvec3 max(lvec3 const&, lvec3 const&);
extern lvec3 min(lvec3 const&, i64);
extern lvec3 min(lvec3 const&, lvec3 const&);
extern lvec3 abs(lvec3 const&);
extern lvec4 clamp(lvec4 const&, i64, i64);
extern lvec4 clamp(lvec4 const&, lvec4 const&, lvec4 const&);
extern lvec4 max(lvec4 const&, i64);
extern lvec4 max(lvec4 const&, lvec4 const&);
extern lvec4 min(lvec4 const&, i64);
extern lvec4 min(lvec4 const&, lvec4 const&);
extern lvec4 abs(lvec4 const&);
extern u8vec4 clamp(u8vec4 const&, u8, u8);
extern u8vec4 clamp(u8vec4 const&, u8vec4 const&, u8vec4 const&);
extern u8vec4 max(u8vec4 const&, u8);
extern u8vec4 max(u8vec4 const&, u8vec4 const&);
extern u8vec4 min(u8vec4 const&, u8);
extern u8vec4 min(u8vec4 const&, u8vec4 const&);
extern u8vec4 abs(u8vec4 const&);
extern uvec2 clamp(uvec2 const&, u32, u32);
extern uvec2 clamp(uvec2 const&, uvec2 const&, uvec2 const&);
extern uvec2 max(uvec2 const&, u32);
extern uvec2 max(uvec2 const&, uvec2 const&);
extern uvec2 min(uvec2 const&, u32);
extern uvec2 min(uvec2 const&, uvec2 const&);
extern uvec2 abs(uvec2 const&);
extern uvec3 clamp(uvec3 const&, u32, u32);
extern uvec3 clamp(uvec3 const&, uvec3 const&, uvec3 const&);
extern uvec3 max(uvec3 const&, u32);
extern uvec3 max(uvec3 const&, uvec3 const&);
extern uvec3 min(uvec3 const&, u32);
extern uvec3 min(uvec3 const&, uvec3 const&);
extern uvec3 abs(uvec3 const&);
extern uvec4 clamp(uvec4 const&, u32, u32);
extern uvec4 clamp(uvec4 const&, uvec4 const&, uvec4 const&);
extern uvec4 max(uvec4 const&, u32);
extern uvec4 max(uvec4 const&, uvec4 const&);
extern uvec4 min(uvec4 const&, u32);
extern uvec4 min(uvec4 const&, uvec4 const&);
extern uvec4 abs(uvec4 const&);
extern ulvec2 clamp(ulvec2 const&, u64, u64);
extern ulvec2 clamp(ulvec2 const&, ulvec2 const&, ulvec2 const&);
extern ulvec2 max(ulvec2 const&, u64);
extern ulvec2 max(ulvec2 const&, ulvec2 const&);
extern ulvec2 min(ulvec2 const&, u64);
extern ulvec2 min(ulvec2 const&, ulvec2 const&);
extern ulvec2 abs(ulvec2 const&);
extern ulvec3 clamp(ulvec3 const&, u64, u64);
extern ulvec3 clamp(ulvec3 const&, ulvec3 const&, ulvec3 const&);
extern ulvec3 max(ulvec3 const&, u64);
extern ulvec3 max(ulvec3 const&, ulvec3 const&);
extern ulvec3 min(ulvec3 const&, u64);
extern ulvec3 min(ulvec3 const&, ulvec3 const&);
extern ulvec3 abs(ulvec3 const&);
extern ulvec4 clamp(ulvec4 const&, u64, u64);
extern ulvec4 clamp(ulvec4 const&, ulvec4 const&, ulvec4 const&);
extern ulvec4 max(ulvec4 const&, u64);
extern ulvec4 max(ulvec4 const&, ulvec4 const&);
extern ulvec4 min(ulvec4 const&, u64);
extern ulvec4 min(ulvec4 const&, ulvec4 const&);
extern ulvec4 abs(ulvec4 const&);

extern bvec2 equal(const dvec2&, const dvec2&);
extern bvec2 greaterThan(const dvec2&, const dvec2&);
extern bvec2 greaterThanEqual(const dvec2&, const dvec2&);
extern bvec2 lessThan(const dvec2&, const dvec2&);
extern bvec2 lessThanEqual(const dvec2&, const dvec2&);
extern bvec3 equal(const dvec3&, const dvec3&);
extern bvec3 greaterThan(const dvec3&, const dvec3&);
extern bvec3 greaterThanEqual(const dvec3&, const dvec3&);
extern bvec3 lessThan(const dvec3&, const dvec3&);
extern bvec3 lessThanEqual(const dvec3&, const dvec3&);
extern bvec4 equal(const dvec4&, const dvec4&);
extern bvec4 greaterThan(const dvec4&, const dvec4&);
extern bvec4 greaterThanEqual(const dvec4&, const dvec4&);
extern bvec4 lessThan(const dvec4&, const dvec4&);
extern bvec4 lessThanEqual(const dvec4&, const dvec4&);
extern bvec2 equal(const vec2&, const vec2&);
extern bvec2 greaterThan(const vec2&, const vec2&);
extern bvec2 greaterThanEqual(const vec2&, const vec2&);
extern bvec2 lessThan(const vec2&, const vec2&);
extern bvec2 lessThanEqual(const vec2&, const vec2&);
extern bvec3 equal(const vec3&, const vec3&);
extern bvec3 greaterThan(const vec3&, const vec3&);
extern bvec3 greaterThanEqual(const vec3&, const vec3&);
extern bvec3 lessThan(const vec3&, const vec3&);
extern bvec3 lessThanEqual(const vec3&, const vec3&);
extern bvec4 equal(const vec4&, const vec4&);
extern bvec4 greaterThan(const vec4&, const vec4&);
extern bvec4 greaterThanEqual(const vec4&, const vec4&);
extern bvec4 lessThan(const vec4&, const vec4&);
extern bvec4 lessThanEqual(const vec4&, const vec4&);
extern bvec2 equal(const ivec2&, const ivec2&);
extern bvec2 greaterThan(const ivec2&, const ivec2&);
extern bvec2 greaterThanEqual(const ivec2&, const ivec2&);
extern bvec2 lessThan(const ivec2&, const ivec2&);
extern bvec2 lessThanEqual(const ivec2&, const ivec2&);
extern bvec3 equal(const ivec3&, const ivec3&);
extern bvec3 greaterThan(const ivec3&, const ivec3&);
extern bvec3 greaterThanEqual(const ivec3&, const ivec3&);
extern bvec3 lessThan(const ivec3&, const ivec3&);
extern bvec3 lessThanEqual(const ivec3&, const ivec3&);
extern bvec4 equal(const ivec4&, const ivec4&);
extern bvec4 greaterThan(const ivec4&, const ivec4&);
extern bvec4 greaterThanEqual(const ivec4&, const ivec4&);
extern bvec4 lessThan(const ivec4&, const ivec4&);
extern bvec4 lessThanEqual(const ivec4&, const ivec4&);
extern bvec2 equal(const lvec2&, const lvec2&);
extern bvec2 greaterThan(const lvec2&, const lvec2&);
extern bvec2 greaterThanEqual(const lvec2&, const lvec2&);
extern bvec2 lessThan(const lvec2&, const lvec2&);
extern bvec2 lessThanEqual(const lvec2&, const lvec2&);
extern bvec3 equal(const lvec3&, const lvec3&);
extern bvec3 greaterThan(const lvec3&, const lvec3&);
extern bvec3 greaterThanEqual(const lvec3&, const lvec3&);
extern bvec3 lessThan(const lvec3&, const lvec3&);
extern bvec3 lessThanEqual(const lvec3&, const lvec3&);
extern bvec4 equal(const lvec4&, const lvec4&);
extern bvec4 greaterThan(const lvec4&, const lvec4&);
extern bvec4 greaterThanEqual(const lvec4&, const lvec4&);
extern bvec4 lessThan(const lvec4&, const lvec4&);
extern bvec4 lessThanEqual(const lvec4&, const lvec4&);
extern bvec4 equal(const u8vec4&, const u8vec4&);
extern bvec4 greaterThan(const u8vec4&, const u8vec4&);
extern bvec4 greaterThanEqual(const u8vec4&, const u8vec4&);
extern bvec4 lessThan(const u8vec4&, const u8vec4&);
extern bvec4 lessThanEqual(const u8vec4&, const u8vec4&);
extern bvec2 equal(const uvec2&, const uvec2&);
extern bvec2 greaterThan(const uvec2&, const uvec2&);
extern bvec2 greaterThanEqual(const uvec2&, const uvec2&);
extern bvec2 lessThan(const uvec2&, const uvec2&);
extern bvec2 lessThanEqual(const uvec2&, const uvec2&);
extern bvec3 equal(const uvec3&, const uvec3&);
extern bvec3 greaterThan(const uvec3&, const uvec3&);
extern bvec3 greaterThanEqual(const uvec3&, const uvec3&);
extern bvec3 lessThan(const uvec3&, const uvec3&);
extern bvec3 lessThanEqual(const uvec3&, const uvec3&);
extern bvec4 equal(const uvec4&, const uvec4&);
extern bvec4 greaterThan(const uvec4&, const uvec4&);
extern bvec4 greaterThanEqual(const uvec4&, const uvec4&);
extern bvec4 lessThan(const uvec4&, const uvec4&);
extern bvec4 lessThanEqual(const uvec4&, const uvec4&);
extern bvec2 equal(const ulvec2&, const ulvec2&);
extern bvec2 greaterThan(const ulvec2&, const ulvec2&);
extern bvec2 greaterThanEqual(const ulvec2&, const ulvec2&);
extern bvec2 lessThan(const ulvec2&, const ulvec2&);
extern bvec2 lessThanEqual(const ulvec2&, const ulvec2&);
extern bvec3 equal(const ulvec3&, const ulvec3&);
extern bvec3 greaterThan(const ulvec3&, const ulvec3&);
extern bvec3 greaterThanEqual(const ulvec3&, const ulvec3&);
extern bvec3 lessThan(const ulvec3&, const ulvec3&);
extern bvec3 lessThanEqual(const ulvec3&, const ulvec3&);
extern bvec4 equal(const ulvec4&, const ulvec4&);
extern bvec4 greaterThan(const ulvec4&, const ulvec4&);
extern bvec4 greaterThanEqual(const ulvec4&, const ulvec4&);
extern bvec4 lessThan(const ulvec4&, const ulvec4&);
extern bvec4 lessThanEqual(const ulvec4&, const ulvec4&);

extern bool all(bvec1 const&);
extern bool any(bvec1 const&);
extern bool all(bvec2 const&);
extern bool any(bvec2 const&);
extern bool all(bvec3 const&);
extern bool any(bvec3 const&);
extern bool all(bvec4 const&);
extern bool any(bvec4 const&);
}

#endif
