#!/usr/bin/env python3
import re, subprocess, sys
from pathlib import Path

keywords = ["_", "tformat"]

# Add a new language here to automatically generate a new .po file!
# Sorting by player count here... but this will get messy if we have many languages
languages = {
    "ru": "Русский",
    "ja": "日本語",
    "fr": "Français",
    "pl": "Polski",
    "de": "Deutsch",
}

srcdir = sys.argv[1]
builddir = sys.argv[2]

# XXX: could pass these in argv from build system
SOURCES = subprocess.run(
    ["find", srcdir + "/src", "-name", "*.cpp", "-o", "-name", "*.h"],
    capture_output=True,
    text=True,
).stdout.splitlines()

# Get list of strings present in SOURCES files
# Similar to xgettext, but for usage in our codebase instead
strings = {}
pattern = re.compile(
    r"\b(?:" + "|".join(keywords) + r')\s*\(\s*"((?:[^"\\]|\\.)*)"\s*[\)\,]'
)
for f in SOURCES:
    for m in pattern.finditer(Path(f).read_text(errors="replace")):
        strings[m.group(1)] = True

# Generate translations.h
# Contains a TRANSLATABLE_STRINGS array and a LANGUAGES array, see i18n.cpp for their use
translations_h = """// Auto-generated by gen_translations.py - do not edit
#pragma once
#include <array>
#include <string_view>

using namespace std::string_view_literals;

inline constexpr auto TRANSLATABLE_STRINGS = std::to_array<std::string_view>({
"""
for s in sorted(strings):
    translations_h += f'    "{s}"sv,\n'
translations_h += """});

inline constexpr auto LANGUAGES = std::to_array<std::pair<std::string_view, std::string_view>>({
    {"en"sv, "English"sv},
"""
for code, lang in languages.items():
    translations_h += f'    {{"{code}"sv, "{lang}"sv}},\n'
translations_h += "});\n\n"

# Compare with existing translations.h - if identical, quit early
# If they differ, this means strings changed or a new language was added, so we need to sync translations.
translations_h_out = Path(f"{builddir}/gen/translations.h")
if translations_h_out.exists() and translations_h_out.read_text() == translations_h:
    sys.exit(0)

print("Strings changed, updating translations.")


# Write translations.h
translations_h_out.write_text(translations_h)

# Write locale_embed.manifest
# With a hack to embed builddir stuff when manifest is expected to look at srcdir
hackdir = Path(builddir).resolve().relative_to(Path(srcdir).resolve())
Path(f"{builddir}/gen/locale_embed.manifest").write_text(
    "\n".join([f"locale_{code} : {hackdir}/gen/{code}.mo" for code in languages])
)

# Regenerate template file to contain latest strings
Path(f"{srcdir}/translations/neomod.pot").unlink()
subprocess.run(
    ["xgettext"]
    + ["--keyword=" + k for k in keywords]
    + [
        "--omit-header",
        "--add-comments=TRANSLATORS",
        "--sort-by-file",
        "-o",
        f"{srcdir}/translations/neomod.pot",
        "--package-name=neomod",
    ]
    + SOURCES
)

# Generate or update language files to match latest languages/strings list
for code, lang in languages.items():
    po = Path(f"{srcdir}/translations/{code}.po")
    if po.exists():
        subprocess.run(
            [
                "msgmerge",
                "-U",
                f"{srcdir}/translations/{code}.po",
                f"{srcdir}/translations/neomod.pot",
            ]
        )
    else:
        print(f"{code}.po doesn't exist, generating a new file.")
        subprocess.run(
            [
                "msginit",
                "--no-translator",
                "-i",
                f"{srcdir}/translations/neomod.pot",
                "-o",
                f"{srcdir}/translations/{code}.po",
                "-l",
                code,
            ]
        )

    subprocess.run(
        [
            "msgfmt",
            "-o",
            f"{builddir}/gen/{code}.mo",
            f"{srcdir}/translations/{code}.po",
        ]
    )
