#!/usr/bin/env python3
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

keywords = ["_", "tformat"]

# Add a new language here to automatically generate a new .po file!
# Sorting by player count here... but this will get messy if we have many languages
languages = {
    "ru": "Русский",
    "ja": "日本語",
    "fr": "Français",
    "pl": "Polski",
    "de": "Deutsch",
}

# Resolve both inputs to absolute paths for unambiguous filesystem ops. xgettext records
# the path string it was given verbatim into .pot/.po `#:` references, so to keep those
# references identical across machines we feed it srcdir-relative paths ("src/App/...")
# and run with cwd=srcdir_abs. This is independent of how the script was invoked
# (make uses ".." / ".", a manual run might use absolute paths) and where builddir lives
# (in-tree under srcdir, sibling, /tmp/..., or anywhere else).
srcdir_abs = Path(sys.argv[1]).resolve()
builddir_abs = Path(sys.argv[2]).resolve()

# builddir is preserved as-passed (typically ".") for manifest entries, so they match
# make's $(builddir) form and the gen/%.mo pattern rule.
builddir = Path(sys.argv[2])

gen_dir = builddir_abs / "gen"
gen_dir.mkdir(parents=True, exist_ok=True)

pot_path = srcdir_abs / "translations" / "neomod.pot"
translations_h_path = gen_dir / "translations.h"
manifest_path = gen_dir / "locale_embed.manifest"

# Translation calls only live in .cpp - .h files contain raw-string OBJ blobs
# and other non-C content that confuses xgettext.
SOURCES = sorted(
    str(p.relative_to(srcdir_abs)) for p in (srcdir_abs / "src").rglob("*.cpp")
)


def parse_pot_msgids(pot_text: str) -> list[str]:
    """Extract msgid payloads from a .pot, preserving C-string escape sequences."""
    msgids: list[str] = []
    current: str | None = None

    def flush() -> None:
        nonlocal current
        if current:
            msgids.append(current)
        current = None

    for raw in pot_text.splitlines():
        s = raw.rstrip()
        if s.startswith("msgid "):
            flush()
            current = _strip_quotes(s[len("msgid "):])
        elif s.startswith("msgid_plural "):
            # plural variant lives at the same index as the singular we just captured
            flush()
        elif s.startswith("msgstr"):
            flush()
        elif s == "" or s.startswith("#"):
            flush()
        elif current is not None and s.startswith('"') and s.endswith('"'):
            current += _strip_quotes(s)
    flush()
    return msgids


def _strip_quotes(s: str) -> str:
    s = s.strip()
    if len(s) >= 2 and s.startswith('"') and s.endswith('"'):
        return s[1:-1]
    return ""


def build_translations_h(msgids: list[str]) -> str:
    out = """// Auto-generated by gen_translations.py - do not edit
#pragma once
#include <array>
#include <string_view>

using namespace std::string_view_literals;

inline constexpr auto TRANSLATABLE_STRINGS = std::to_array<std::string_view>({
"""
    for s in sorted(set(msgids)):
        out += f'    "{s}"sv,\n'
    out += """});

inline constexpr auto LANGUAGES = std::to_array<std::pair<std::string_view, std::string_view>>({
    {"en"sv, "English"sv},
"""
    for code, lang in languages.items():
        out += f'    {{"{code}"sv, "{lang}"sv}},\n'
    out += "});\n\n"
    return out


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


# Regenerate .pot into a temp file so we can decide whether to actually update it.
with tempfile.NamedTemporaryFile("w", suffix=".pot", dir=str(gen_dir), delete=False) as tmp:
    temp_pot = Path(tmp.name)

try:
    subprocess.run(
        ["xgettext"]
        + ["--keyword=" + k for k in keywords]
        + [
            "--omit-header",
            # --no-wrap matches the msgmerge flag below; otherwise xgettext wraps msgid lines
            # at 78 cols and msgmerge re-wraps differently per platform.
            "--no-wrap",
            # Keep the source-file reference for translator tooling, but drop line numbers so
            # `#:` comments don't churn whenever unrelated code edits shift line offsets.
            "--add-location=file",
            # Pick up "// xgettext: no-c-format" markers on problem strings (e.g. "100% to 150%"
            # that would otherwise get spurious c-format flags).
            "--add-comments=TRANSLATORS",
            # tformat's first argument is a fmt::format_string, so let msgfmt --check-format validate
            # translator format mismatches. We deliberately do NOT pass --flag=_:1:no-c-format - that
            # would globally disable c-format detection for every _() string, which is too broad: it
            # would silently hide format-string bugs if anyone ever feeds an _() string to printf or
            # similar. The literal-`%` strings (ModSelector.cpp "100%" etc.) use per-call-site
            # `// xgettext: no-c-format` comments to suppress the flag locally instead.
            "--flag=tformat:1:c++-format",
            "--sort-by-file",
            "-o", str(temp_pot),
            "--package-name=neomod",
        ]
        + SOURCES,
        cwd=str(srcdir_abs),
        check=True,
    )

    msgids = parse_pot_msgids(temp_pot.read_text(encoding="utf-8"))
    new_translations_h = build_translations_h(msgids)

    # If translations.h content is unchanged, the set of translatable strings is the same.
    # Skip rewriting .pot/.po too, to avoid line-number churn on unrelated source edits.
    if (
        translations_h_path.exists()
        and translations_h_path.read_text(encoding="utf-8") == new_translations_h
    ):
        # Make sure the manifest exists for first-build-after-clean scenarios.
        manifest_content = "\n".join(f"locale_{code} : {builddir}/gen/{code}.mo" for code in languages) + "\n"
        write_if_changed(manifest_path, manifest_content)
        sys.exit(0)

    print("Strings changed, updating translations.")

    shutil.move(str(temp_pot), str(pot_path))
    temp_pot = None  # don't unlink in finally
finally:
    if temp_pot is not None and temp_pot.exists():
        temp_pot.unlink()

translations_h_path.write_text(new_translations_h, encoding="utf-8")

# Generate or update language .po files to match latest strings
for code, lang in languages.items():
    po = srcdir_abs / "translations" / f"{code}.po"
    if po.exists():
        subprocess.run(
            # --no-wrap keeps msgstr lines unbroken, so .po output is identical regardless of
            # the locale/libc/msgmerge version that produced it (default-wrapped output churns
            # across platforms). --add-location=file matches the xgettext flag above so the
            # `#:` references in .po stay aligned with .pot if msgmerge ever runs standalone.
            ["msgmerge", "-U", "--backup=none", "--no-wrap", "--add-location=file", str(po), str(pot_path)],
            check=True,
        )
    else:
        print(f"{code}.po doesn't exist, generating a new file.")
        subprocess.run(
            [
                "msginit",
                "--no-translator",
                "-i", str(pot_path),
                "-o", str(po),
                "-l", code,
            ],
            check=True,
        )

# locale_embed.manifest is consumed within the same build, so entries are written
# using $(builddir)-relative paths to match gen_binary_embed.py's -F flag (which does not
# prepend --base-dir) and the gen/%.mo pattern rule in Makefile.am.
manifest_content = "\n".join(f"locale_{code} : {builddir}/gen/{code}.mo" for code in languages) + "\n"
write_if_changed(manifest_path, manifest_content)
