name: linux-multiarch
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'cmake-win/**/*'
      - 'tools/**/*'
      - '**/*.md'
      - '.clangd-template'
      - '.gitignore'
      - '.git-blame-ignore-revs'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'cmake-win/**/*'
      - 'tools/**/*'
      - '**/*.md'
      - '.clangd-template'
      - '.gitignore'
      - '.git-blame-ignore-revs'
  workflow_dispatch:

env:
  CCACHE_DIR: /tmp/.ccache

jobs:
  build:
    runs-on: ubuntu-latest
    container: whrvt/neosu-linux:latest
    strategy:
      matrix:
        arch: [x64, x32]
        include:
          - arch: x64
            host: x86_64-pc-linux-gnu
          - arch: x32
            host: i686-pc-linux-gnu
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v6.0.1

      - name: Set up build directory
        run: |
          mkdir -p "$(pwd)"/build-out/build
          mkdir -p "$(pwd)"/build-out/.ltocache-gcc
          mkdir -p "$(pwd)"/build-out/.ltocache-clang
          mkdir -p ${{ env.CCACHE_DIR }}

      - name: Cache dependency tarballs
        uses: actions/cache@v5.0.1
        with:
          path: |
            build-aux/cache
          key: tarballs-linux-${{ matrix.arch }}-${{ hashFiles('configure.ac', 'Makefile.am') }}
          restore-keys: |
            tarballs-linux-${{ matrix.arch }}-
            tarballs-linux-

      - name: Cache built dependencies
        uses: actions/cache@v5.0.1
        with:
          path: |
            build-out/build/deps
          key: deps-linux-${{ matrix.arch }}-${{ hashFiles('configure.ac', 'Makefile.am') }}
          restore-keys: |
            deps-linux-${{ matrix.arch }}-

      - name: ccache
        uses: actions/cache@v5.0.1
        with:
          path: |
            ${{ env.CCACHE_DIR }}
            build-out/.ltocache-gcc
            build-out/.ltocache-clang
          key: ccache-linux-${{ matrix.arch }}-${{ github.sha }}
          restore-keys: |
            ccache-linux-${{ matrix.arch }}-

      - name: Building neomod
        run: |
          ./autogen.sh
          export MAKEFLAGS="-j$(nproc)"
          export CCACHE_DIR="${{ env.CCACHE_DIR }}"
          cd build-out && \
          ../configure --disable-tests \
            ${{ (github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/dev') && '--disable-strip' || '' }} \
            --with-audio="bass,soloud" --with-renderer="opengl,sdlgpu" --host=${{ matrix.host }} && \
          make install

      - name: Package artifacts (fix symlinks)
        run: |
          cd build-out
          zip -r -y -8 bin.zip ./dist/bin-*/
          rm -rf dist/*
          mv bin.zip dist/

      - uses: actions/upload-artifact@v6.0.0
        with:
          name: neomod-linux-${{ matrix.arch }}
          path: build-out/dist
